### ISSUE TITLE
bug: return value is always "any"

### ISSUE THREAD

**Issue by patrickbussmann** [ionic-team/capacitor-docgen#30]
Hello,

I created a new capacitor plugin: https://github.com/paystory-de/capacitor-headwind-mdm
And whenever I run this `docgen` command it generates a wonderful README.md - except the `returns`.
Its always:

    isConnected() => any

And

**Returns:** <code>any</code>

Any ideas? 😉

**Comment by dragermrb** [comment]
Update to version v0.0.18, fails on version 0.0.10

**Comment by jcesarmobile** [comment]
yeah, not sure why it doesn't pick latest version of docgen when it has `^` on the dependency, but I updated the plugin generator to use ^0.0.18, so it's fixed on the generator now
