### ISSUE TITLE
bug: Non-accessible APIs from external dependencies are part of the output

### ISSUE THREAD

**Issue by robingenz** [ionic-team/capacitor-docgen#36]
Hi, 
thank you very much for this helpful generator.
I have the following problem since version `0.1.1`:
APIs of external dependencies are included, which are not available via the plugin API (`definitions.ts`).

Here you can find an example: https://github.com/robingenz/capacitor-firebase-authentication/pull/122/files

In this project I have increased the version of docgen to 0.1.1 and updated the markdown. There are now many interfaces included (partly also twice), which are not available at all.

**Comment by jcesarmobile** [comment]
fixed on https://github.com/ionic-team/capacitor-docgen/pull/39

**Comment by WoodyWoodsta** [comment]
Not sure why but I'm getting this issue on `v0.2.1`.

I've imported a type library, and exported a few of its types, but the generated docs include all exports by that library (which, as in the original description of this issue, are not available outside of the plugin).
