### ISSUE TITLE
Do not show "Returns" for void functions

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor-docgen#4]
When docs are generated for void functions, this is what appears:

<img width="129" alt="image" src="https://user-images.githubusercontent.com/236501/95898183-80cfbd00-0d43-11eb-9cb7-b199e2207114.png">

The **Returns** line should just be removed for void functions

**Comment by adamdbradley** [comment]
Closed https://github.com/ionic-team/capacitor-docgen/commit/9ae065359309851e6919313bb59d9ab9d250002b
